### PR TITLE
Example of failing test with extensions

### PR DESCRIPTION
**Pull request by bkaney**

### CODE REVIEW

**Comment by brianpos** [comment]
The cause is due to the lack of a primitive value to go along with the extension value.

**Comment by bkaney** [comment]
> The cause is due to the lack of a primitive value to go along with the extension value.

Yes, this is the problem. You shouldn't need a primitive value to have the extension value.

**Comment by plynchnlm** [comment]
I think the problem has been fixed in 2.14.5, but I am not sure why these test cases did not get merged along with the fix.

**Comment by plynchnlm** [comment]
Closing, as these changes are on the master branch, though partly relocated, which I suppose is why these commits do not show up there.

**Comment by bkaney** [comment]
I think that’s the bug. It’s not required to have a primitive value.

**Pull request closed without merging**
