### PR TITLE
fix-datetime-comparison

### PR DESCRIPTION
**Pull request by commi**

### CODE REVIEW

**Comment by plynchnlm** [comment]
Thanks for the pull request.  Could you add a test (or tests) that shows the bug that is fixed by these changes?  (Or, at least post a test case.)

**Comment by commi** [comment]
Hi, this fixes the tests
- group: 6.1.3. != (Not Equals) › group: Dates & Times › DateTime literal compared with different precision DateTime in resource: @2018-02-02 != date1

- group: 6.1.3. != (Not Equals) › group: Dates & Times › DateTime literal compared with different precision DateTime (1): @2018 != @2018-02
- group: 6.1.1. = (Equals) › group: Dates & Times › DateTime literal compared with different precision DateTime in resource: @2018-02-02 = date1
- group: 6.1.1. = (Equals) › group: Dates & Times › DateTime literal compared with different precision DateTime (1): @2018 = @2018-02

in the existing test cases, which previously failed

**Comment by plynchnlm** [comment]
For me, all of the tests pass on both the master branch and your fix-datetime-comparison branch.  Sometimes the local timezone makes a difference.  What timezone are you in?

**Comment by plynchnlm** [comment]
Okay, I tried:  TZ=CET jest and the tests fail on master, but pass on your branch.

**Comment by commi** [comment]
> Okay, I tried: TZ=CET jest and the tests fail on master, but pass on your branch.

Jep, it's because the change to UTC converts the `@2018` to 2017-12-31T23:00:00. This should be ignored for dates without time. If you just _add_ hours to UTC (like in the US timezones) it works by accident.

**Comment by plynchnlm** [comment]
TZ=EST bin/fhirpath -e '@2018-03 != @2018-02-03' -r '{}' returns true when it should return false.  That is true on master as well.  (There is a test that incorrectly enforces that.)  Anyway, that is not a problem with your pull request, and we can look into fixing that problem.

**Comment by plynchnlm** [comment]
Is this urgent for you?  It looks like it will probably be a couple of weeks before we get this merged.

**Comment by commi** [comment]
Not urgent, i just just stumbled upon this while writing tests for my other PR.
Right now we are using our own fork anyway because we use React Native and that requires some hacks to include fhirpath.js, that should not be merged.

**Comment by commi** [comment]
> TZ=EST bin/fhirpath -e '@2018-03 != @2018-02-03' -r '{}' returns true when it should return empty. 

i think this is current. The precision is different but we know they cant be equal (different month). And the timezone should _not_ be adjusted in any direction, because the are dates only. (for times (without date), this should also apply)

**Comment by plynchnlm** [comment]
Your changes are now merged (as of 2.1.5), but via a different pull request (including your commit), so I am closing this one.  Thanks for the fix!

**Pull request merged**
