### PR TITLE
minimum changes to get ie 10 to run fhirpath page

### PR DESCRIPTION
**Pull request by bpacJoseph**
Added babel to compile to a version of javascript that ie 10 understands

Added polyfills for missing ie 10 functionality

### CODE REVIEW

**Comment by plynchnlm** [comment]
This is the kind of fix I was hoping for-- a change to the webpack configuration.  The one concern I have is the increase of resulting build/fhirpath.js of nearly 50% (210k->301k).  I am wondering whether the file size could be reduced by setting a browser target of >= ie10.

**Comment by plynchnlm** [comment]
You missed one webpack.config.js file, in browser-build.  That's the build of the file that is ready-to-use in a browser.

**Comment by niquola** [comment]
Do we know what exactly does not work in IE 10? What kind of polifils do we need? ( I'm wondered anybody still use this old stuff).

**Comment by niquola** [comment]
Can we just make second build for fossil browsers?

**Comment by plynchnlm** [comment]
> 
> 
> Do we know what exactly does not work in IE 10? What kind of polifils do we need? ( I'm wondered anybody still use this old stuff).

Apparently, for Cerner, SMART on FHIR apps need to support IE 10.  I don't know which polyfills are needed, though it might be possible to determine that.  I just know that the demo page does not work with IE 10 (without this pull request).

**Comment by plynchnlm** [comment]
> 
> 
> Can we just make second build for fossil browsers?

Yes, that could be done for the browser-build.  For the demo page, I think we need just one build (though I guess for the demo page the download size does not matter so much).

**Comment by niquola** [comment]
Can we get error messages for IE? Or let's force Cerner to upgrade built-in browsers  ;) How old is IE 10?

**Comment by plynchnlm** [comment]
> My understanding is that for Cerner, SMART on FHIR apps need to support IE 10. I don't know which polyfills are needed, though it might be possible to determine that. I just know that the demo page does not work with IE 10 (without this pull request).

Actually, at least for our SMART on FHIR apps, we pull in fhirpath.js as an npm package, in which case the browser-build is not used.  We would need the same webpack.config.js settings in our app when building that, to target IE 10 and pull in polyfills.  I guess this would just help the apps that do not use npm/webpack, but rely on our browser build files.

**Comment by plynchnlm** [comment]
> 
> 
> Can we get error messages for IE? Or let's force Cerner to upgrade built-in browsers ;) How old is IE 10?

My information was from September 2018, and there were plans I think within the next year or two (from then, and if I remember correctly) to move to Edge.  Unfortunately, not only do we have to wait for that upgrade to happen, we have to wait for the EHR customers to upgrade to the new version which uses Edge.  I was told that might be as long as 5 years.

**Comment by niquola** [comment]
let's call this build - cerner-please-upgrade-your-extremely-old-browser-fhirpath.js

**Comment by bpacJoseph** [comment]
> If you don't want to work further on this, that's fine. I appreciate the contribution, and it is a good starting point for us.

Unfortunately I have run out of work time for this for the immediate future.
We were hoping to get it into one of our products that has a requirement to run in IE 10.

**Comment by plynchnlm** [comment]
> Unfortunately I have run out of work time for this for the immediate future.
> We were hoping to get it into one of our products that has a requirement to run in IE 10.

That is understandable.  I assume you are able to use your fork while waiting for this to get finished and merged?

**Comment by bpacJoseph** [comment]
This fork can be used while we wait

**Comment by bpacJoseph** [comment]
While working on this I was able to get a browser package building. Do you want an issue/PR for this?

**Comment by plynchnlm** [comment]
> 
> 
> While working on this I was able to get a browser package building. Do you want an issue/PR for this?

I'm not sure what you mean, because we already had a browser package-- but maybe you mean you got it working in IE 10?

It looks like that change ("update browserbuild webpack config")  was pushed, and is now already a part of this pull request, so I think a new PR is probably not necessary.

**Comment by plynchnlm** [comment]
I experimented with configuring babel for IE 10 (by changing "presets: ['@babel/preset-env']" to "presets: [['@babel/preset-env', {targets: {"ie": "10"}}]]" in both webpack.config.js and in browser-build/webpack.config.js) but there was no difference in the build size.  I confirmed my syntax was correct by changing {"ie": "10"} to {"chrome": "65} which did slightly reduce the build size.  So, I think this pull request can proceed as is.

**Comment by bpacJoseph** [comment]
> I'm not sure what you mean, because we already had a browser package-- but maybe you mean you got it working in IE 10?

I was able to get a smaller npm package
Below are the files in the packages

smaller 
image


current
image

**Comment by plynchnlm** [comment]
> 
> I was able to get a smaller npm package
> Below are the files in the packages

Smaller is good.  I think you are right-- let's make that a separate PR, since this one is semi-approved and working.

**Pull request merged**
